
#redis服务配置
spring:
  redis:
    host: localhost
    port: 6379
#数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.javasm.mapper: debug

app:
  token:
#    私钥
    privateKey: DvNRuK6C+h1P/1LVjU9mZG+pywIGrnuLUR43KRi8b9Q=
#    过期时间
    expireTime: 15
server:
  port: 8080